# Generated by Django 3.0.5 on 2020-04-19 11:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('problem', '0002_auto_20200419_1554'),
    ]

    operations = [
        migrations.AlterField(
            model_name='probleminout',
            name='inp',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='probleminout',
            name='out',
            field=models.TextField(blank=True),
        ),
    ]
